liip_imagine:
  driver: "imagick"
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: media/cache
  filter_sets:
    cache: ~
    thumb_small:
      quality: 90
      filters:
        thumbnail: { size: [300, 300], mode: outbound }
    thumb_big:
      quality: 100
      filters:
        thumbnail: { size: [1080, 720], mode: inset }
