vich_uploader:
  db_driver: orm

  mappings:
    video_mapping:
      uri_prefix: /uploads/gallery_videos
      upload_destination: "%kernel.project_dir%/public/uploads/gallery_videos"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    photo_mapping:
      uri_prefix: /uploads/gallery_photos
      upload_destination: "%kernel.project_dir%/public/uploads/gallery_photos"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    comment_images_mapping:
      uri_prefix: /uploads/comment_images
      upload_destination: "%kernel.project_dir%/public/uploads/comment_images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
