name: remi_delecroix
type: "php:8.2"
mounts:
  "var/log":
    source: local
    source_path: log
  "var/cache":
    source: local
    source_path: cache
  "web/uploads":
    source: local
    source_path: uploads
disk: 256
relationships:
  database: "db:mysql"
hooks:
  build: |
    set -e
  deploy: |
    set -e
    php bin/console cache:clear
web:
  locations:
    "/":
      root: "web"
      passthru: "/index.php"
