controllers:
  resource: ../src/Controller/
  type: attribute

security_question:
  path: /security-question
  controller: App\Controller\SecurityQuestionController::index

app_logout:
  path: /logout
  controller: Symfony\Bundle\SecurityBundle\Controller\LogoutController
