parameters:
  locale: "fr"
  uploadDirectory: "%kernel.project_dir%/public/uploads"
  imagesDirectory: "images"

services:
  _defaults:
    autowire: true
    autoconfigure: true
  
  App\EventSubscriber\AccessInterceptorSubscriber:
    arguments:
      $router: '@router'

  admin.photo:
    class: App\Admin\PhotoAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\Photo,
          manager_type: orm,
          label: Photos,
        }

  admin.video:
    class: App\Admin\VideoAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\Video,
          manager_type: orm,
          label: Vidéos,
        }

  admin.category:
    class: App\Admin\CategoryAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\Category,
          manager_type: orm,
          label: Catégories,
        }

  admin.comment:
    class: App\Admin\CommentAdmin
    arguments: [~, App\Entity\Comment, App\Admin\CommentAdminController]
    tags:
      - {
          name: sonata.admin,
          manager_type: orm,
          group: "Content",
          label: "Comment",
        }

  admin.user:
    class: App\Admin\UserAdmin
    tags:
      - {
          name: sonata.admin,
          model_class: App\Entity\User,
          manager_type: orm,
          label: Utilisateurs,
        }

  Intervention\Image\ImageManager:
    class: Intervention\Image\ImageManager

  App\:
    resource: "../src/*"
    exclude:
      - "../src/DependencyInjection/*"
      - "../src/Entity/*"
      - "../src/Migrations/*"
      - "../src/Tests/*"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  App\Admin\CommentAdminController:
    public: true
    arguments:
      - "@sonata.admin.pool"
      - "@sonata.admin.request.fetcher"
    calls:
      - [setContainer, ["@service_container"]]
