parameters:
  locale: "fr"
  uploadDirectory: "%kernel.project_dir%/public/uploads"
  imagesDirectory: "images"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Intervention\Image\ImageManager:
    class: Intervention\Image\ImageManager

  App\:
    resource: "../src/*"
    exclude:
      - "../src/DependencyInjection/*"
      - "../src/Entity/*"
      - "../src/Migrations/*"
      - "../src/Tests/*"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]
